# Generated by Django 2.0.5 on 2018-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180608_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Nos',
            field=models.IntegerField(null=True),
        ),
    ]
